# Generated by Django 4.0.5 on 2022-11-06 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='작성시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='content',
            field=models.TextField(null=True, verbose_name='작성시간'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='examinee_id',
            field=models.CharField(max_length=40, null=True, verbose_name='응시자'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='test_name',
            field=models.CharField(max_length=40, null=True, verbose_name='과목명'),
        ),
    ]
