# Generated by Django 4.0.5 on 2022-11-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0002_fileupload_upload_time_alter_fileupload_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='content',
            field=models.TextField(null=True, verbose_name='내용'),
        ),
    ]
