# Generated by Django 4.0.5 on 2022-11-06 16:40

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0004_remove_fileupload_examinee_id_fileupload_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='imgfile',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='postings/'),
        ),
    ]
