# Generated by Django 4.0.5 on 2022-09-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('top_fixed', models.BooleanField(default=False, verbose_name='상단고정')),
            ],
            options={
                'verbose_name': 'NoticeBoard',
                'verbose_name_plural': 'NoticeBoard',
                'db_table': 'NoticeBoard',
            },
        ),
    ]
