# Generated by Django 4.0.5 on 2022-09-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='수정일'),
        ),
    ]
