# Generated by Django 4.0.5 on 2022-10-30 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(db_column='시험번호', max_length=24)),
                ('cheating_time', models.DateTimeField()),
                ('cheating_type', models.CharField(db_column='부정행위 유형', max_length=24)),
                ('admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='감독관id')),
                ('admin_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_name', to=settings.AUTH_USER_MODEL, verbose_name='감독관id')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
