# Generated by Django 4.0.5 on 2022-10-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheating',
            name='cheating_type',
            field=models.CharField(db_column='cheating_type', max_length=24, verbose_name='부정행위유형'),
        ),
        migrations.AlterField(
            model_name='cheating',
            name='test_id',
            field=models.CharField(db_column='testid', max_length=24, verbose_name='시험번호'),
        ),
    ]
