# Generated by Django 4.0.5 on 2022-10-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameraApp', '0002_alter_cheating_cheating_type_alter_cheating_test_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheating',
            old_name='user_id',
            new_name='examinee_id',
        ),
    ]
