# Generated by Django 4.0.5 on 2022-10-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraApp', '0003_rename_user_id_cheating_examinee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheating',
            name='cheating_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='시간'),
        ),
    ]
