# Generated by Django 4.0.5 on 2022-10-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraApp', '0004_alter_cheating_cheating_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheating',
            name='cheating_type',
            field=models.TextField(db_column='cheating_type', verbose_name='부정행위유형'),
        ),
    ]
