# Generated by Django 4.0.5 on 2022-10-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraApp', '0007_cheating_cheating_date_alter_cheating_cheating_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheating',
            name='cheating_date',
        ),
        migrations.AlterField(
            model_name='cheating',
            name='cheating_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='시간'),
        ),
    ]
