# Generated by Django 4.0.5 on 2022-11-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraApp', '0009_cheating_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheating',
            name='admin_id',
            field=models.CharField(default='id', max_length=24, verbose_name='관리자id'),
        ),
        migrations.AlterField(
            model_name='cheating',
            name='examinee_id',
            field=models.CharField(default='id', max_length=24, verbose_name='응시자id'),
        ),
    ]
