# Generated by Django 4.0.5 on 2022-10-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False, verbose_name='시험 코드')),
                ('test_name', models.CharField(max_length=128, verbose_name='시험 과목')),
                ('start_time', models.DateField(auto_now=True, verbose_name='시작시간')),
                ('end_time', models.DateField(auto_now=True, verbose_name='종료시간')),
                ('test_type', models.BooleanField(default=False, verbose_name='시험 유형')),
            ],
            options={
                'verbose_name': 'testTable',
                'verbose_name_plural': 'testTable',
                'db_table': 'testTable',
            },
        ),
    ]
