# Generated by Django 4.0.5 on 2022-10-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableApp', '0002_test_test_date_alter_test_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_date',
            field=models.DateField(null=True, verbose_name='시험날짜'),
        ),
    ]
