# Generated by Django 4.0.5 on 2022-10-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableApp', '0006_test_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(db_column='test_type', default='paper', max_length=10),
        ),
    ]
