# Generated by Django 4.0.5 on 2022-10-20 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tableApp', '0007_alter_test_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examinee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_Room', models.DateTimeField(auto_now_add=True, verbose_name='입장시간')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testadmin', to='tableApp.test', verbose_name='감독관id')),
                ('examinee_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='응시자')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcode', to='tableApp.test', verbose_name='시험 코드')),
            ],
        ),
    ]
