# Generated by Django 4.0.5 on 2022-10-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableApp', '0008_examinee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='examinee',
            table='Examinee',
        ),
    ]
