# Generated by Django 4.0.5 on 2022-10-22 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tableApp', '0011_alter_examinee_test_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinee',
            name='examinee_name',
        ),
        migrations.AddField(
            model_name='examinee',
            name='examinee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='응시자 아이디'),
        ),
    ]
