# Generated by Django 4.0.5 on 2022-10-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableApp', '0014_examinee_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='head_count',
            field=models.IntegerField(default=0, verbose_name='인원수'),
        ),
    ]
